import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider , SidebarTrigger } from "@/components/ui/sidebar";
import {AppSidebar}  from "@/components/seeker-sidebar"
import { Title } from "@/components/title";
import { CONFIG } from "../config";

const projectTitle : string = CONFIG.TITLE;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: `${projectTitle}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}>
      <SidebarProvider>
        <AppSidebar/>
        <main className="w-full">
          <SidebarTrigger />
          {/*<Title/>*/}
          {children}
        </main>
      </SidebarProvider>
      </body>
    </html>
  );
}
