import type { Metadata } from "next";
import { CONFIG } from "../config";
import RootLayout from "./RootLayout"; // Import the client component

export const metadata: Metadata = {
  title: CONFIG.TITLE,
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout>{children}</RootLayout>;
}
